TERM_DICTIONARY = {
    "broadband": "Broadband is a high-speed internet connection that is always on.",
    "bandwidth": "Bandwidth is the maximum rate of data transfer across a network",
    "ethernet": "Ethernet is a wired connection that is faster and less susceptible to interference",
    "wifi" : "Wi-Fi is a wireless connection that is very convenient but can be slower and less reliable due to interference or signal loss.",
    "IP address" : "An IP address is a unique identifier assigned to each device on a network, they allow for communication between devices.",
    "MAC" : "A MAC address is a unique identifer for the hardware of a device.",
    "DNS" : "Domain Name System (DNS) is a system that translates lengthy, hard to remember IP addresses into domain names in a human-readable format.",
    "LAN" : "Local Area Network (LAN) is a network that connects devices in a small geographic area, such as a home or office.",
    "WAN" : "Wide Area Network (WAN) is a network that connects devices over a large geographic area, such as multiple offices or cities.",
    "NAT" : "Network Address Translation (NAT) is a process that allows multiple devices on a network to share a single public IP address.",
    "firewall" : "A firewall is a security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules, these may be installed by your ISP.",
    "port forwarding" : "Port forwarding is a technique that allows devices on a private network to be accessible from the internet by forwarding network traffic from a specific port to a device on the network.",
    "latency" : "Latency is the time it takes for data to travel from one point to another in a network. It is measured in milliseconds (ms).",
    "throughput" : "Throughput is the amount of data that can be transferred over a network in a given amount of time. It is measured in bits per second (bps).",
    "packet" : "A packet is a unit of data that is transmitted over a network. It contains the data being sent, as well as information about the source and destination of the data.",
    "router" : "A router is a device that connects multiple devices in a network and directs data traffic between them. It also connects the network to the internet.",
    "switch" : "A switch connects devices in a network together and controls the flow between them, but does not connect the network to the internet.",
    "modem" : "A modem connects your network to your Internet Service Provider (ISP), which allows you to access the internet.",
    "VPN" : "A Virtual Private Network (VPN) is a secure connection that allows you to access the internet privately and securely by routing your connection through a server.",
    "proxy" : "A proxy server is an intermediary server that sits between your device and the internet. It can be used to hide your IP address and access restricted content.",
    "HTTP" : "Hypertext Transfer Protocol, known as HTTP, is used to transfer data over the internet, the foundation of the world wide web.",
    "HTTPS" : "Hypertext Transfer Protocol Secure, known as HTTPS, is a version of HTTP that encrypts data for secure communication over the web.",
    "TCP" : "Transmission Control Protocol (TCP) is a connection-oriented protocol that ensures data is delivered reliably and in the correct order.",
    "UDP" : "User Datagram Protocol (UDP) is a connectionless protocol that is faster but less reliable than TCP.",
    "megabit" : "A megabit is a unit of data that is equal to 1 million bits. It is commonly used to measure data transfer rates.",
    "megabyte" : "A megabyte is a unit of data that is equal to 1 million bytes. It is commonly used to measure file sizes. You may see this when downloading images or apps."
}

COMPARISON_DICTIONARY = {
    "bandwidthbroadband": "Bandwidth is the maximum rate of data transfer across a network, whereas broadband is a high-speed internet connection that is always on.",
    "ethernetwifi": "Ethernet is a wired connection that is faster and more reliable than Wi-Fi, which is a wireless connection that is more convenient but slower.",
    "ipmac" : "An IP address is a unique identifier assigned to each device on entry to a network, while a MAC address is a unique identifier assigned to the hardware of a device.",
    "ipv4ipv6" : "IPv4 uses 32-bit addresses, allowing for 4.3 billion unique addresses, while IPv6 uses 128-bit addresses, allowing for 340 undecillion unique addresses!",
    "latencythroughput" : "Latency is the time it takes for data to travel from one point to another in a network, while throughput is the amount of data that can be transferred over a network in a given amount of time.",
    "modemrouter" : "A modem connects your network to your Internet Service Provider (ISP), while a router connects multiple devices in a network and directs data traffic between them.",
    "routerswitch" : "A router connects devices in a network and connects them to the internet, whereas a switch connects devices in a network and controls data flow between them.",
    "vpnproxyserver" : "A VPN is a secure connection that allows you to access the internet privately and securely, while a proxy server is an intermediary server that sits between your device and the internet.",
    "httphttps" : "HTTPS is a secure version of HTTP that encrypts data for secure communication over the web. Both can be used, but HTTPS is more secure.",
    "megabitmegabyte" : "A megabyte is a unit of data equal to 8 megabits. Megabits are used for measuring download speeds, megabytes are used to measure storage/file sizes ."
}