TERM_DICTIONARY = {
    "broadband": "Broadband is ",
    "bandwidth": "Bandwidth is the maximum rate of data transfer across a network",
    "ethernet": "Ethernet is a wired connection that is faster and less susceptible to interference",
    "wifi" : "Wi-Fi is a wireless connection that is very convenient but can be slower and less reliable due to interference or signal loss.",
    "IP address" : "explanation here",
    "MAC" : "explanation here",
    "DNS" : "explanation here",
    "LAN" : "explanation here",
    "WAN" : "explanation here",
    "NAT" : "explanation here",
    "firewall" : "explanation here",
    "port forwarding" : "explanation here",
    "latency" : "explanation here",
    "throughput" : "explanation here",
    "packet" : "A packet is a unit of data that is transmitted over a network. It contains the data being sent, as well as information about the source and destination of the data.",
    "router" : "A router is a device that connects multiple devices in a network and directs data traffic between them. It also connects the network to the internet.",
    "switch" : "A switch connects devices in a network together and controls the flow between them, but does not connect the network to the internet.",
    "modem" : "A modem connects your network to your Internet Service Provider (ISP), which allows you to access the internet.",
    "VPN" : "explanation here",
    "proxy" : "explanation here",
    "HTTP" : "Hypertext Transfer Protocol, known as HTTP, is used to transfer data over the internet, the foundation of the world wide web.",
    "HTTPS" : "Hypertext Transfer Protocol Secure, known as HTTPS, is a version of HTTP that encrypts data for secure communication over the web.",
    "TCP" : "explanation here",
    "UDP" : "explanation here",
    "megabit" : "A megabit is a unit of data that is equal to 1 million bits. It is commonly used to measure data transfer rates.",
    "megabyte" : "A megabyte is a unit of data that is equal to 1 million bytes. It is commonly used to measure file sizes. You may see this when downloading images or apps."
}

COMPARISON_DICTIONARY = {
    "bandwidthbroadband": "Bandwidth is the maximum rate of data transfer across a network, whereas broadband is a high-speed internet connection that is always on.",
    "ethernetwifi": "Ethernet is a wired connection that is faster and more reliable than Wi-Fi, which is a wireless connection that is more convenient but slower.",
    "IPNAT" : "explanation here",
    "ipv4ipv6" : "explanation here",
    "latencythroughput" : "explanation here",
    "modemrouter" : "A modem connects your network to your Internet Service Provider (ISP), while a router connects multiple devices in a network and directs data traffic between them.",
    "routerswitch" : "A router connects devices in a network and connects them to the internet, whereas a switch connects devices in a network and controls data flow between them.",
    "subnetmaskgateway" : "explanation here",
    "vpnproxyserver" : "explanation here",
    "httphttps" : "explanation hhbmnn here",
    "megabitmegabyte" : "A megabyte is a unit of data equal to 8 megabits. Megabits are used for measuring download speeds, megabytes are used to measure storage/file sizes ."
}